nome = str(input('Digite o seu nome: ')).strip()
mai = nome.upper()
min = nome.lower()
letras = (len(nome)-nome.count(' '))
prinome = nome.find(' ')
print('Seu nome em maiúsculas é : {}.'.format(mai))
print('Seu nome em minúsculas é: {}.'.format(min))
print('Seu nome tem {} letras.'.format(letras))
print('Seu primeiro nome tem {} letras.'.format(prinome))