print('Este programa calcula a média de duas notas de prova de um aluno.')
nome = str(input('Qual o nome do aluno? '))
n1 = float(input('Digite a primeira nota: '))
n2 = float(input('Digite a segunda nota: '))
med = ((n1+n2)/2)
print('A média das provas de {} é {:.1f}'.format(nome, med))